### ISSUE TITLE
Allow multiple instances of the same option

### ISSUE THREAD

**Issue by chewi** [nathwill/chef-systemd#100]
It is quite common in systemd to need to state the same option multiple times, such as `ListenStream` in a socket file. Unless I'm mistaken, the cookbook currently doesn't provide a way to do that. Array values are simply joined with a space, which is arguably less useful, though I suppose it could help when deep merging attributes. I can't think of any other intuitive syntax, short of making the attribute setter append instead of replace. That's probably a bad idea.

**Comment by nathwill** [comment]
yeah, that's about the short of it, as things stand. best strategy for now is to use multiple drop-in resources. systemd does lexically-ordered file loading, so if order matters, you can name/number the drop-ins accordingly.

**Comment by chewi** [comment]
Thanks for the suggestion, hadn't considered that.
