### ISSUE TITLE
How can I pass params to :enable

### ISSUE THREAD

**Issue by Suman-Plivo** [nathwill/chef-systemd#102]
Is it possible to pass params to :enable action. Like i want to enable multiple services by doing "systemctl enable service_name@{1..4}.service". This will enable 4 services simultaneously with the names service_name@1.service, service_name@2.service, service_name@3.service, service_name@4.service. Can this be done in chef recipe, other than executing inside bash service.

**Comment by nathwill** [comment]
i wouldn't think so, though it should be easy to test. iirc, the `{1..4}` syntax relies on bash expanding the argument before the command is executed (i.e. bash expands `systemctl enable blah@{1..4}.service` to `systemctl enable blah@1.service blah@2.service blah@3.service blah@4.service` before the arguments are passed to the `systemctl` binary), and i'm fairly sure once the arg gets passed into the underlying execute resource, the bash expansion won't be happening.
