### ISSUE TITLE
implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

### ISSUE THREAD

**Issue by jklare** [nathwill/chef-systemd#104]
Hi,

after upgrading the systemd cookbook from 2.1.3 to 3.0.0 i get this runtime error:

 RuntimeError
  ------------
  implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

 Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/systemd/libraries/mixin.rb:36:in `block in build_dsl'
...cut...

Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/systemd/libraries/mixin.rb:

   29:
   30:        module ClassMethods
   31:          def build_dsl
   32:            define_method(:method_missing) do |name, *args, &blk|
   33:              if @context && respond_to?("#{@context}_#{name}".to_sym)
   34:                send("#{@context}_#{name}".to_sym, *args, &blk)
   35:              else
   36>>               super
   37:              end
   38:            end
   39:
   40:            define_method(:respond_to_missing?) do |name, include_private|
   41:              if @context && respond_to?("#{@context}_#{name}".to_sym)
   42:                true
   43:              else
   44:                super(name, include_private)
   45:              end

  Platform:
  ---------
  x86_64-linux

For me it looks like this is not related to my wrapper cookbook, but is an actual error in the systemd mixin lib itself.

Cheers,
Jan

**Comment by florian-asche** [comment]
Same issue here.

**Comment by nathwill** [comment]
interesting, can you provide your chef version & example(s) of the relevant use of systemd-cookbook provided resources?

**Comment by nathwill** [comment]
pushed a fix in 3.0.1, wanna give it a shot?

**Comment by jklare** [comment]
Thanks for the fast response, but i think this did not fix it. Now the "resource name" is handed over in "*args", which then again leads to an undefined method.

**Comment by nathwill** [comment]
@jklare huh. can you advise as to which chef version you're using, and any reproduction steps? i'm not seeing this problem at all when running the unit/integration tests, so it's hard to test for.

**Comment by jklare** [comment]
@nathwill i am currently using the systemd resource still in its pre v3 style (which is why i did not post the full thing instantly). The resource which works with v2 looks like this:

```
systemd_service 'percona_clustercheck@' do
  description 'MySQL Clustercheck'
  after %w(network.target)
  service do
    user 'nobody'
    exec_start "/usr/bin/clustercheck clusterchecker #{chkpass}"
    standard_input 'socket'
  end
end
````

Since the argument/attribute "description" (was moved to unit_description i guess) does not exist anymore in chef-systemd v3, i would expect it to fail with something like this:

```
NoMethodError
  -------------
  undefined method `description' for Custom resource systemd_service from cookbook systemd
```

With the current version 3.0.1 it fails like this instead:

```
NoMethodError
  -------------
  undefined method `MySQL Clustercheck' for Custom resource systemd_service from cookbook systemd
```

Which in my opinion is due to the missing "name" argument in line 36 of libraries/mixin.rb. I will push a PR for this in case this fixes it for somebody else, i will not be able to test it in my setup until the beginning of next week i think.

Cheers,
Jan

**Comment by nathwill** [comment]
good catch, thanks for the PR. i'll drop this in 3.0.2
