### ISSUE TITLE
%i not compatible with chef 11

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-systemd#11]
this is a known issue; not sure what the market penetration for chef 12 vs chef 11 is (i'd expect pretty high in orgs that are fast-moving enough to need systemd...), but we might want to fix this for backwards compat? leaving this here for user feedback in case it's actually needed.

**Comment by nathwill** [comment]
let's call it a won't fix unless we get some actual user reports of needing this.

**Comment by bheuvel** [comment]
Hi @nathwill , I just ran into this issue. Problem is that servers here are deployed by default with a Chef11 client, upgraded with Omnibus to 12. Problem is that this cookbook already breaks at compile phase, even before the omnibus resource can run.

Created PR #76 which replaces code which I ran into, and works on my machine :wink: 

But if one/my report is not enough, perhaps you could mention in the README that this cookbook is not compatible with Chef 11?

**Comment by nathwill** [comment]
@bheuvel thanks so much for the PR! i just merged it and things LGTM, so i released your changes as version 1.1.1, which is now on the supermarket. let us know if you run into any other trouble!

**Comment by bheuvel** [comment]
@nathwill thanks so much for the quick response and release :smiley:! Thanks to this quick release I can use this immediately without (temporary) workarounds!

**Comment by nathwill** [comment]
:boom:
