### ISSUE TITLE
Cookbook creating unit files in the wrong location

### ISSUE THREAD

**Issue by domingosnovo** [nathwill/chef-systemd#112]
Normally the `systemd_service` resource will create unit files in the right location (that is, `/etc/systemd/system/<service_name>.service`).

But, if a service is configured to run as a specific user (by defining the directive `user <some_user>`) it will create the unit file in `/etc/systemd/user/<service_name>.service` instead.

The problem is, Systemd will not bother to search for unit files in `/etc/systemd/user` by default. This will make a resource such as the below:

```ruby
systemd_service 'my-service' do
  action [:create, :enable]
  service do
    type 'simple'
    working_directory '/opt/my-service'
    exec_start '/opt/my-service/bin/run.py'
    user 'my-user'
    kill_mode 'process'
    restart 'always'
    restart_sec '5s'
  end
  install do
    wanted_by 'network-online.target'
  end
end
```

Return a error such as this one when executed:

```
    ================================================================================
    Error executing action `enable` on resource 'systemd_service[my-service]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    systemd_unit[my-service.service] (/var/chef/cookbooks/systemd/libraries/resource_factory.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl --user enable my-service.service ----
    STDOUT:
    STDERR: Failed to connect to bus: No such file or directory
    ---- End output of /bin/systemctl --user enable my-service.service ----
    Ran /bin/systemctl --user enable my-service.service returned 1

```

**Comment by domingosnovo** [comment]
I am of the opinion that you don't need to write the unit file to `/etc/systemd/user`, and it is enough to just add `User=<my-user>` to the unit file (while still writing it to `/etc/systemd/system`), since this is the location systemd expects to find services running upon boot.

Another possibility is to use the full path of the unit file when defining a user in the chef resource, as it will allow Systemd to properly find the unit file:

```bash
root@my-instance:/root# systemctl enable /etc/systemd/user/my-service.service
Created symlink from /etc/systemd/system/network-online.target.wants/my-service.service to /etc/systemd/user/my-service.service.
Created symlink from /etc/systemd/system/my-service.service to /etc/systemd/user/my-service.service.
root@my-instance:/root#
```

**Comment by nathwill** [comment]
sorry for the slow response, i've been away on vacation.

you should use the `service_user` property directly for this; using `user` inside the service block never reaches `service_user` property via the method_missing rescue, because `systemd_unit` resource has a `user` property for systemd's user services (not all systemd instances are pid-1 system instances).

hope that helps explain what's going on there.
