### ISSUE TITLE
No longer supporting repeated directives

### ISSUE THREAD

**Issue by dbresson** [nathwill/chef-systemd#116]
Some directives, like ExecStartPre can appear multiple times. It appears with version 3 of this cookbook that is no longer supported.

**Comment by jacbib-adsk** [comment]
I'm noticing this in my work too.  Would really appreciate seeing a fix!

**Comment by nathwill** [comment]
please correct me if i'm wrong, but i believe you can solve this with:
- drop in units (lexical ordering)
- the `precursor` property (see https://github.com/nathwill/chef-systemd/pull/111)
