### ISSUE TITLE
LimitInterval Compatibility Options

### ISSUE THREAD

**Issue by petracvv** [nathwill/chef-systemd#121]
At some point systemd renamed their `LimitInterval` options to have the `LimitIntervalSec` form (https://github.com/systemd/systemd/commit/f0367da7d1a61ad698a55d17b5c28ddce0dc265a). 

However, certain enterprise distributions such as CentOS7 are using a version of systemd before this change. Since this cookbook is using the new name, I cannot configure the any of the `LimitInterval` options because only the `LimitIntervalSec` options are supported by the cookbook. According to the systemd docs, both the new and old options are supported. 

Can the old options be added for compatibility reasons?

I will look into a pull request but I don't know when I can get around to it.

**Comment by nathwill** [comment]
@petracvv yeah absolutely. in cases where an option has been renamed, including both in the cookbook works perfectly fine, as we only inject the one specified by the user. don't worry about submitting a PR, i've got some time set aside today to work on some other things on this cookbook, and can work this into it while i'm at it.

thanks for flagging this!

**Comment by petracvv** [comment]
Thanks! I can help with any testing if you need it.

**Comment by nathwill** [comment]
fixed at https://github.com/nathwill/chef-systemd/pull/122
