### ISSUE TITLE
Editing systemd_service in recipe doesn't trigger a systemctl daemon-reload

### ISSUE THREAD

**Issue by azuretek** [nathwill/chef-systemd#124]
I'm writing a recipe that creates a `systemd_service` and ran into a problem. I thought it was working fine but then I had to make a change to the `systemd_service` resource and noticed it didn't trigger a `systemctl daemon-restart` execution after updating the resource. I have `triggers_reload` set to true but as far as I can tell this only has any effect when creating and deleting resources.

**Comment by nathwill** [comment]
@azuretek can you provide a sample resource (original and changed version) so we can replicate?

**Comment by nathwill** [comment]
daemon-reload is only necessary when the on-disk unit representation has changed. per the description, that happens (i.e. create/delete actions), so barring further clarification, closing this as a non-issue.
