### ISSUE TITLE
Bridge netdev expects VLAN ID

### ISSUE THREAD

**Issue by kelleyk** [nathwill/chef-systemd#126]
I'm trying to replace the following `netdev` configuration file with a `systemd_netdev` resource.  All that it does is set a static, locally-administered hardware address for a bridge device.

```
[NetDev]
Name = foo
Kind = bridge
MACAddress = 86:d3:7f:7c:32:7c
```

Here's the equivalent Chef resource that I've come up with.
```
systemd_netdev 'foo' do
  net_dev_name 'foo'
  net_dev_kind 'bridge'
  net_dev_mac_address '86:d3:7f:7c:32:7c'
end
```

When I run Chef, I get a validation error insisting that `vlan_id` must be set.  However, per `systemd.netdev(5)`, the `[VLAN]` section may only be present if the netdev's `Kind` is `vlan` (whereas this is a `bridge`).

```
[2018-01-10T16:39:15-08:00] ERROR: systemd_netdev[foo] (some-cookbook::default line 43) had an error: Chef::Exceptions::ValidationFailed: vlan_id is required
```

I think that this could be resolved by allowing `vlan_id` to be unset (less strict), or by looking at `netdev_kind` and then either requiring that it be unset or applying the existing validation depending on whether it's a `vlan` device or not (more strict).

Thank you for making this module available to everyone, and thanks in advance for your help!

**Comment by nathwill** [comment]
great catch @kelleyk, thanks for filing this. i think we'd be better off relaxing the requirement, as i don't think we can guarantee that the kind has been set before the vlan_id, and introducing ordering dependencies on the resource properties seems like a pain. do you want to file a PR?

**Comment by kelleyk** [comment]
I'm not particularly fluent in either Ruby or Chef, but I'm happy to take a whack at it; let me see what I can come up with.

**Comment by nathwill** [comment]
okey doke. i'm heading out for the night, but if you get stuck, let me know and i can get a patch submitted and a new release cut first thing in the morning.

**Comment by nathwill** [comment]
this is out in 3.1.6, thanks again for the report!

**Comment by kelleyk** [comment]
Thank _you_ for the prompt fix!
