### ISSUE TITLE
multiple exec_start_pre

### ISSUE THREAD

**Issue by cyrille-polymtl** [nathwill/chef-systemd#129]
I want to be able to have multiple exec_start_pre defined for my services, however, the documentation say it is a string, and in my test it seems to take only the last entry.
Is there an easy hack ? or should I create two services with dependencies ?

**Comment by nathwill** [comment]
yeah, the limitation is irritating, but fortunately easy to work around. systemd drop-ins use lexical ordering, so the way i've been solving this is to create a series of drop-ins:

```ruby
systemd_service_drop_in '00-stage0-prestart' do
  override 'my-app'
  service do
    exec_start_pre '/usr/bin/pre-start stage0'
  end
  action :create
end

systemd_service_dop_in '01-stage1-prestart' do
  override 'my-app'
  service do
    exec_start_pre '/usr/bin/pre-start stage1'
  end
  action :create
end
```

there's also the `precursor` property, so you can also do something like:

```ruby
systemd_service_drop_in 'my-overrides' do
  override 'my-app'
  precursor({ 'ExecStartPre' => '/usr/bin/pre-start stage0' })
  service do
    exec_start_pre '/usr/bin/pre-start stage1'
  end
end
```

the precursor property is also on the non-drop-in unit resources, so if you have your own unit defined and you're not using drop-ins to override a vendor unit, you could do something like:

```ruby
systemd_service 'my-app' do
  precursor({ 'ExecStartPre' => '/usr/bin/pre-start stage0' })
  unit do
    description 'my super cool app'
  end
  service do
    exec_start_pre '/usr/bin/pre-start stage1'
    exec_start '/usr/bin/my-app -d'
  end
  install do
    wanted_by 'multi-user.target'
  end
  action :create
end
```

if you need more than 2, you can get fancy with hash keys:

```ruby
p = {}.compare_by_identity
p['ExecStartPre'] = '/usr/bin/pre-start stage0'
p['ExecStartPre'] = '/usr/bin/pre-start stage1'
p['ExecStartPre'] = '/usr/bin/pre-start stage2'

systemd_service 'my-app' do
  precursor p
  unit do
    description 'my super cool app'
  end
  service do
    exec_start '/usr/bin/my-app -d'
  end
  install do
    wanted_by 'multi-user.target'
  end
  action :create
end
```

hope that helps!

**Comment by cyrille-polymtl** [comment]
Hi,
Thanks for the answer,
my chef/ruby didn't like the compare_by_identity, something it doesn't have or understand.
but I was able to use the 'drop_in' to add my extra service_exec_start_pre.
