### ISSUE TITLE
Patch version number updated on a breaking change

### ISSUE THREAD

**Issue by weevil44** [nathwill/chef-systemd#135]
Bumping the version to 3.2.3 breaks the cookbook when using pessimistic locking and an older version of Chef

I am pinning like so
`depends 'systemd', '~> 3.2.2'`
and using Chef version 12.13

Now I get the following error:
`       [2018-05-01T17:42:54+00:00] ERROR: Cookbook 'systemd' version '3.2.3' depends on chef version [">= 12.19"], but the running chef version is 12.13.37
`

I think the version should have gone to 4.0.0 even though it was a very minor change

**Comment by nathwill** [comment]
noted
