### ISSUE TITLE
timesyncd Help....

### ISSUE THREAD

**Issue by masikmos** [nathwill/chef-systemd#136]
I dont understand how i can edit file 

`/etc/systemd/timesyncd.conf`

and set parameter 

```
[Time]
NTP = bla bla bla
FallbackNTP = bla bla bla
```

can you give me some example please. Thx!

**Comment by nathwill** [comment]
using the [systemd_timesyncd](https://github.com/nathwill/chef-systemd#systemd_timesyncd) resource, you can configure timesyncd via drop-ins (e.g. /etc/systemd/timesyncd.conf.d/masikmos.conf).

[here's](https://github.com/nathwill/chef-systemd/blob/master/test/fixtures/cookbooks/test/recipes/daemons.rb#L24-L29) how we exercise the resource for testing, and the [resultant configuration](https://github.com/nathwill/chef-systemd/blob/master/test/integration/default/daemons_spec.rb#L44-L46).
