### ISSUE TITLE
Re-add the ability to create drop-ins for daemons

### ISSUE THREAD

**Issue by mitchellrj** [nathwill/chef-systemd#143]
For example, prior to 3.0.0, one could achieve a journald drop-in with:
```
        systemd_journald "my-overrides" do
          drop_in true
          max_retention_sec 3600
          notifies :restart, "service[systemd-journald]", :delayed
        end
```

but this doesn't appear to be possible any more with the new drop-in structure?

**Comment by nathwill** [comment]
hi @mitchellrj, thanks for the inquiry. in v3.0 we got rid of the direct configuration editing for daemon configuration files, so the `systemd_journald` resource automatically creates drop-ins now

i.e. [this resource](https://github.com/nathwill/chef-systemd/blob/master/test/fixtures/cookbooks/test/recipes/daemons.rb#L2-L8) will create [this configuration](https://github.com/nathwill/chef-systemd/blob/master/test/integration/default/daemons_spec.rb#L1-L12).

hope that helps!
