### ISSUE TITLE
Chef 17 :kind_of issue 

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [nathwill/chef-systemd#146]
System Info:
     ------------
     chef_version=17.0.242
     platform=debian
     platform_version=10
     ruby=ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
     program_name=/usr/bin/chef-client
     executable=/opt/chef/bin/chef-client

`Chef::Exceptions::ValidationFailed: Property manager_default_limit_nofile must be one of: {:kind_of=>[String, Integer], :desired_state=>false}!  You passed 10000.`

**Comment by nathwill** [comment]
can you show the resource definition?

**Comment by everythings-gonna-be-alright** [comment]
@nathwill 
```
systemd_system 'global' do
    manager_default_limit_nofile 10000
end
```

**Comment by renchap** [comment]
This is the same issues as #144, I just submitted a PR with a fix.
