### ISSUE TITLE
add systemd_snapshot resource

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-systemd#25]
[snapshots](http://www.freedesktop.org/software/systemd/man/systemd.snapshot.html) are pretty cool.

**Comment by ranjib** [comment]
i dont think we should support this as part of the cookbook. systemd snapshots are designed to for emergency or diagnostic uses, where `systemctl snapshot` command will be used to temporary terminate service/resource, it generates the snapshot file for restoration purpose. i could not find a lot of resource on this, except the minimal man page. i'll dig further.

**Comment by ranjib** [comment]
found some info here: http://blog.fpmurphy.com/2013/09/systemd-snapshots.html

**Comment by nathwill** [comment]
The articles awfully old,so I'm not sure how accurately it reflects the current state of snapshot support, but I'm totally onboard with saying we won't implement them in the cookbook, as the use case definitely seems more adhoc than something you'd actually want to do regularly.
