### ISSUE TITLE
what's left for 1.0?

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-systemd#50]
@ranjib @stevendanna wanted to see if there's any changes or enhancements in particular you guys had in mind for a 1.0 release. i've been using this cookbook pretty extensively at $JOB and am pretty happy so far with the overall resource semantics and effectiveness, so as far as i'm concerned we're ready to go.
- [x] docs (example uses)
- [x] docs (resource actions)
- [x] full set of chefspec matchers

**Comment by stevendanna** [comment]
@nathwill If you think this is ready to go, I say go for it.  I know a number of people are using it productively already.

**Comment by ranjib** [comment]
@nathwill it will be awesome if we can ramp up the documentations. I am also seeing several bugs (like service enable does not actually start the service upon reboot), which is probably more of a systemd issue.
finally, if we can document a section on readme regarding how this compares with the core service resource with systemd as provider.
none of these are blocker, but having docs will be awesome for a 1.0 release :-)

kudos to you for all the hard work

**Comment by ranjib** [comment]
btw, i have only tested it on my raspberry pi cluster, running ubuntu 15.04/systemd -219.
another thing i was wondering is, how we plan to maintain directive compatibilities across systemd versions. new binaries are also being added with newer versions of systemd

**Comment by nathwill** [comment]
thanks for the quick feedback guys :)

@stevendanna cool, thanks.

@ranjib i just did a big doc overhaul to fill them out some more, though there's still definitely lots more to do... i'm curious about the service enable not starting service on boot, are these services that are 'static' in the `systemctl status xyz.service` command before chef 'enables'? there's some state handling in the provider that considers 'static' to be kind of hands-off, so seems like a possible spot for something like you mentioned. happy to help troubleshoot if you can provide some specifics!

>  finally, if we can document a section on readme regarding how this compares with the core service resource with systemd as provider.

good idea. so far, i've been trying to avoid using `systemd_service` resources to do lifecycle actions that the service resource handles, and just adding a service resource to go along them since that's what our team's more used to seeing, and it feels a little weird to 'take over' service mgmt from chef-core. definitely a little conflicted about best approach there.

> how we plan to maintain directive compatibilities across systemd versions. new binaries are also being added with newer versions of systemd

this is something that's already showing up in our test-kitchen matrix, and is pretty irritating, as it adds a lot of complexity to test-kitchen. excluding testing, though, i think it's pretty easy to deal with in the cookbook. over time i'd expect more binaries and directives will be added, and some might be removed, but we can just "keep up" through gradual additive process as features emerge. i don't think we need to worry about a directive changing meaning or anything. so rather than "versioning" our resource attributes and trying to only make them available on supported platforms (sounds nightmarish), we can just let cookbook consumers determine which directives are usable for their situation (same issue they'd have just reading the systemd docs).

**Comment by nathwill** [comment]
alright, cutting 1.0 in https://github.com/nathwill/chef-systemd/pull/57
