### ISSUE TITLE
Support --enable-split-usr

### ISSUE THREAD

**Issue by stevendanna** [nathwill/chef-systemd#54]
I haven't been able to dig deeply into this yet, but I'm opening this as a placeholder.  Ubuntu 15.04 compiles systemd with `--enable-split-usr` which means that some things will be found in `/lib/systemd` rather than `/usr/lib/systemd`.  This looks like it might affect the udevd recipe; however, we have testing on 15.04 around that platform so I might be missing something.

**Comment by nathwill** [comment]
nice find @stevendanna , confirmed this is an issue for the udevd recipe, systemd-udevd and other systemd-xyz binaries are under /lib/systemd, and not under /usr/lib/systemd...

**Comment by nathwill** [comment]
and from the sound of it, Ubuntu's not in any hurry to implement the /usr merge, so we should definitely plan to accommodate split usr.

**Comment by stevendanna** [comment]
Thanks!
