### ISSUE TITLE
coredumps not (fully?) configured

### ISSUE THREAD

**Issue by boldandbusted** [nathwill/chef-systemd#83]
Howdy. I need to enable core dumps on my CentOS 7.1 system. I have this stanza being applied from chef (after including chef-systemd):

```
systemd_coredump 'compress-coredumps' do
  compress true
  storage 'external'
  keep_free '15%' 
end
```

And the kitchen/vagrant run (Edited, let me know if you need more):

```
-----> Chef Omnibus installation detected (install only if missing)                                               [416/682]
       Transferring files to <default-centos-71>
       Starting Chef Client, version 12.6.0
       resolving cookbooks for run list: ["ripple-enable-core-files::default"]
       Synchronizing Cookbooks:
         - ripple-enable-core-files (0.1.0)
         - limits (1.0.0)
         - sysctl (0.7.0)
         - systemd (1.1.2)
         - ohai (2.1.0)
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: ripple-enable-core-files::default
         * systemd_coredump[compress-coredumps] action create
           * directory[/etc/systemd/coredump.conf.d] action create
             - create new directory /etc/systemd/coredump.conf.d
             - restore selinux security context
           * execute[compress-coredumps.coredump-systemd-reload] action nothing (skipped due to action :nothing)
           * file[/etc/systemd/coredump.conf.d/compress-coredumps.conf] action create
             - create new file /etc/systemd/coredump.conf.d/compress-coredumps.conf
             - update content in file /etc/systemd/coredump.conf.d/compress-coredumps.conf from none to 8cf296
             --- /etc/systemd/coredump.conf.d/compress-coredumps.conf   2016-02-03 19:46:12.462066418 +0000
             +++ /etc/systemd/coredump.conf.d/.compress-coredumps.conf20160203-12656-jnl7si     2016-02-03 19:46:12.4620664
18 +0000
             @@ -1 +1,5 @@
             +[Coredump]
             +Storage=external
             +Compress=yes
             +KeepFree=15%
             - restore selinux security context
           * execute[compress-coredumps.coredump-systemd-reload] action run (skipped due to only_if)    
```

And my stanza in my recipe:

But, no core files are generated:

```
~/work_gits/ripple-chef/ (jesse-implement-rhel-core-file-enabling) kitchen login
/home/jesse/.rvm/gems/ruby-2.2.2/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialize
d constant HTTPClient::CookieManager
/home/jesse/.rvm/gems/ruby-2.2.2/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of Cookie
Manager was here
Last login: Wed Feb  3 19:46:36 2016 from 10.0.2.2
[vagrant@default-centos-71 ~]$ uptime
 19:51:59 up 0 min,  1 user,  load average: 0.16, 0.04, 0.02
[vagrant@default-centos-71 ~]$ sudo su -
Last login: Wed Feb  3 19:46:41 UTC 2016 on pts/0
[root@default-centos-71 ~]# sleep 100 &
[1] 1991
[root@default-centos-71 ~]# kill -11 1991
[root@default-centos-71 ~]# cd /var/lib/systemd/
[1]+  Segmentation fault      sleep 100  (wd: ~)
(wd now: /var/lib/systemd)
[root@default-centos-71 systemd]# cd coredump/
[root@default-centos-71 coredump]# ls
[root@default-centos-71 coredump]# dmesg | tail
[    3.974164] 00:00:00.024432 main     OS Product: Linux
[    3.974188] 00:00:00.024486 main     OS Release: 3.10.0-229.el7.x86_64
[    3.974209] 00:00:00.024508 main     OS Version: #1 SMP Fri Mar 6 11:36:42 UTC 2015
[    3.974228] 00:00:00.024526 main     OS Service Pack: #1 SMP Fri Mar 6 11:36:42 UTC 2015
[    3.974258] 00:00:00.024547 main     Executable: /opt/VBoxGuestAdditions-5.0.6/sbin/VBoxService
00:00:00.024550 main     Process ID: 638
00:00:00.024551 main     Package type: LINUX_64BITS_GENERIC
[    3.977255] 00:00:00.027569 main     5.0.6 r103037 started. Verbose level = 0
[    5.440168] floppy0: no floppy controllers found
[    5.440204] work still pending
[root@default-centos-71 coredump]#
```

Any ideas? Thanks! :) If you need more info or experiments, glad to help.

**Comment by boldandbusted** [comment]
Oh, FYI, I had been going down this road before I found that this cookbook has this capability via Systemd:

http://www.kibinlabs.com/re-enabling-core-dumps-redhat-7/

**Comment by nathwill** [comment]
hi @boldandbusted,

thanks for the issue report! 

yeah, the `systemd_coredump` resource is currently limited to just configuring the systemd-coredump utility via the config file, though i agree it would be really nice if we provided a way to go further and fully enable coredumps on a system (probably via a recipe).

from reading that article, it sounds like the likely missing piece is the `LimitCore` exec directive for a specific service, or a system-wide `DefaultLimitCORE` in `/etc/systemd/system.conf` (or via the systemd_system resource as a drop-in), though I haven't tested to confirm. looking at our own centos 7.1 systems, i'm also noticing that they seem to be missing the `/usr/lib/sysctl.d/50-coredump.conf` file described in [the docs](http://www.freedesktop.org/software/systemd/man/systemd-coredump.html) that points the `kernel.core_pattern` sysctl to systemd-coredump, so guessing that'll be needed as well?

as soon as i can, I'll see about adding a coredump test to the test suite (SIGSEV ftw) and adding a full example to the readme once it's confirmed as working. in the meantime, i _think_ this cookbook has all the required components needed to manually tweak all the relevant settings, though it doesn't provide a recipe to do the heavy lifting (yet).

**Comment by boldandbusted** [comment]
:+1: :cake:

**Comment by nathwill** [comment]
so after thinking about this some more, i think configuring the system for coredumps is ultimately out of scope. this cookbook and chef itself provide the primitives needed to customize coredump behavior, but actually combining it all in a platform-agnostic way goes well beyond the scope of 'systemd' things, so closing this as wont-fix
