### ISSUE TITLE
Allow user to specify rendered file mode

### ISSUE THREAD

**Issue by mfischer-zd** [nathwill/chef-systemd#95]
systemd configuration files can contain sensitive information (e.g. secret keys in the environment or other places).  Allow the user to specify a file mode (e.g. `'400'`) when declaring a unit.

**Comment by nathwill** [comment]
in general my approach for environment stuff is to use `EnvironmentFile` and configure that with appropriate permissions. you can do environment interpolation in the systemd unit if the sensitive data needs to be passed as part of another directive, using something like:

```
EnvironmentFile=/etc/sysconfig/myapp
ExecStart=/usr/bin/myapp -u myuser -p ${PASSWORD}
```

that said, i'm certainly open to the idea of making the unit file permissions configurable as well. you interested in trying to put together a PR?

**Comment by mfischer-zd** [comment]
I agree that that the above pattern is more idiomatic.  This is a low-priority request for that reason.

**Comment by nathwill** [comment]
solution for this is going to need to happen upstream on the chef-core `systemd_unit` resource, as we've upstreamed a generic unit resource a while back. closing this issue straight away, but i'll be opening a PR on chef-core momentarily.
