### ISSUE TITLE
Can't declare dependencies on interfaces or devices

### ISSUE THREAD

**Issue by mfischer-zd** [nathwill/chef-systemd#96]
It is perfectly legal to depend on a `netdev`, `network` or `device` unit in systemd, but this cookbook doesn't like it:

```
[2016-09-01T00:28:26+00:00] ERROR: Option requires's value ["sys-subsystem-net-devices-eth1.device"] is a valid unit !
```

Also, the error message is nonsensical.

**Comment by nathwill** [comment]
👍 nice catch.
